<a href="chapitre.php?chapitre=chapitre1" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark  animate__animated animate__tada">Ch1</a>
<a href="chapitre.php?chapitre=chapitre2" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch2</a>
<a href="chapitre.php?chapitre=chapitre3" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch3</a>
<a href="chapitre.php?chapitre=chapitre4" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch4</a>
<a href="chapitre.php?chapitre=chapitre5" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch5</a>
<a href="chapitre.php?chapitre=chapitre6" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch6</a>
<a href="chapitre.php?chapitre=chapitre7" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch7</a>
<a href="chapitre.php?chapitre=chapitre8" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch8</a>
<a href="chapitre.php?chapitre=chapitre9" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch9</a>
<a href="chapitre.php?chapitre=chapitre10" class="bg-secondary.bg-gradient text-decoration-none btn-outline-dark animate__animated animate__tada">Ch10</a>